void functionWificonnect();
void initLed(int ledPin);
void initCapteurChaleur();
void initVentilo();
void setChauffage();
void setVentilo();
void setAlerte();
void setEtatRegulateurTemperature();
int lireCapteurLumiere();
float lireCapteurChaleur();
void setBandeLed();
void setLed();
void setDetectorFire();
void informationPrint();
const char* makeText(int i);
const char* makeText2(int i);
void readData();
void setMaxTemperature();
void setMinTemperature();
